targetNamespace: ""
parameters: {}
packages:
  - name: users
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: createUser
        binary: false
        main: ""
        runtime: "nodejs:18"
        web: raw
        triggers:
          - name: trigger-hello
            sourceType: scheduler
            sourceDetails:
              cron: "* * * * *"
              withBody:
                name: "mike"
        parameters: {}
        environment: {}
        annotations: {}
        limits:
          memory: 1024
          timeout: 900000
  - name: file
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: upload
        binary: false
        main: ""
        runtime: "nodejs:18"
        web: raw
        parameters: {}
        environment: {}
        annotations: {}
        limits:
          memory: 1024
          timeout: 900000

environment:
  DATABASE: ${DATABASE}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  PROPELAUTH_API_KEY: ${PROPELAUTH_API_KEY}
  PROPELAUTH_URL: ${PROPELAUTH_URL}
  PROPELAUTH_VERIFIER_KEY: ${PROPELAUTH_VERIFIER_KEY}
  PROPELAUTH_ISSUER: ${PROPELAUTH_ISSUER}
