targetNamespace: ""
parameters: {}
packages:
  - name: sample
    environment: {}
    parameters: {}
    annotations: {}
    actions:
      - name: hello
        binary: false
        main: ""
        runtime: "nodejs:default"
        web: raw
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
LOG_DESTINATIONS: ${_self.FUNCTIONS_LOG_DESTINATION_JSON}
