targetNamespace: ""
parameters: {}
packages:
  - name: users
    environment: {}
    parameters: {}
    annotations: {}
    actions:
      - name: createUser
        binary: false
        main: ""
        runtime: "nodejs:default"
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits:
          memory: 1024
          timeout: 120000

environment:
  DATABASE: ${DATABASE}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}



