targetNamespace: ""
parameters: {}
packages:
  - name: users
    environment: {}
    parameters: {}
    annotations: {}
    actions:
      - name: createUser
        binary: false
        main: ""
        runtime: "nodejs:default"
        web: raw
        triggers:
          - name: trigger-hello
            sourceType: scheduler
            sourceDetails:
              cron: "* * * * *"
          - name: "daily-trigger"
            sourceType: scheduler
            sourceDetails:
              cron: "0 21 * * *"
        parameters: {}
        environment: {}
        annotations: {}
        limits:
          memory: 1024
          timeout: 900000

environment:
  DATABASE: ${DATABASE}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  LOG_DESTINATIONS: ${LOG_DESTINATIONS}



