targetNamespace: ""
parameters: {}
packages:
  - name: sample
    environment: {}
    parameters: {}
    annotations: {}
    actions:
      - name: hello
        binary: false
        main: ""
        runtime: "nodejs:default"
        web: raw
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
environment:
  LOG_DESTINATIONS: ${LOG_DESTINATIONS}
  CERT_DATA:  ${CERT_DATA}
  DATABASE: ${DATABASE}
  DATABASE_PASSWORD:  ${DATABASE_PASSWORD}
  NODE_ENV: ${NODE_ENV}
  TEST: ${TEST}
